apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/dependsOn
        value: [{name: aws-load-balancer-controller, namespace: kube-system}]
  - target:
      kind: HelmRelease
      name: flagger
    patch: |-
      - op: add
        path: /spec/dependsOn
        value: [{name: nginx-ingress-controller, namespace: ingress-nginx}]
