apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno
  - namespaces
  - helm-repositories
  - observability
  - aws-load-balancer-controller
  - nginx-ingress-controller
  - cert-manager
  - flagger
  - flagger-loadtester
  - flux-image-automation
